repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.4.2'  # Use the revision sha / tag you want to point at
    hooks:
    -   id: isort
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    - id: flake8

